import pandas as pd
import numpy as np


# ── 22.1 Executive Brief Generator ───────────────────────────────────────────

def generate_executive_brief(
    df_employees: pd.DataFrame,
    df_flight_risk: pd.DataFrame,
    df_centrality: pd.DataFrame,
    df_sentiment: pd.DataFrame,
    scenario_results: pd.DataFrame,
    recruitment_metrics: dict = None,
) -> str:
    """
    Generate one-page people intelligence brief untuk CEO/CHRO.
    Bisa dijadwalkan otomatis setiap Senin pagi — zero manual work.
    """
    if recruitment_metrics is None:
        recruitment_metrics = {
            "avg_time_to_fill_days": 32,
            "top_source_by_quality": "LinkedIn (quality-of-hire score: 4.1/5)",
        }

    critical_count = int((df_flight_risk["flight_risk_score"] >= 0.80).sum())
    high_count     = int((df_flight_risk["flight_risk_score"].between(0.60, 0.80)).sum())
    avg_engagement = df_employees["engagement_score"].mean()
    total_hc       = len(df_employees)

    top_risk = df_flight_risk.merge(
        df_employees[["employee_id", "full_name", "department"]], on="employee_id"
    ).nlargest(1, "flight_risk_score").iloc[0]

    central_connectors = df_centrality[
        df_centrality["network_role"] == "Central Connector"
    ]["employee_id"].tolist()
    cc_at_risk = df_flight_risk[
        df_flight_risk["employee_id"].isin(central_connectors) &
        (df_flight_risk["flight_risk_score"] >= 0.60)
    ]

    avg_sentiment = df_sentiment["compound"].mean() if "compound" in df_sentiment.columns else 0.0

    scenario_worst = scenario_results.loc[
        scenario_results["est_productivity_impact_pct"].idxmax()
    ]

    # Retention ROI
    high_risk_emp     = df_flight_risk[df_flight_risk["flight_risk_score"] >= 0.6]
    merged_risk       = df_employees.merge(high_risk_emp, on="employee_id")
    replacement_cost  = int(merged_risk["monthly_salary"].mean() * 6 * len(merged_risk))
    retention_cost    = int(merged_risk["monthly_salary"].mean() * 12 * 0.10 * len(merged_risk))
    net_savings       = replacement_cost - retention_cost

    brief = f"""
╔══════════════════════════════════════════════════════════════╗
║           ORGPULSE — PEOPLE INTELLIGENCE BRIEF              ║
║                      Desember 2024                          ║
╚══════════════════════════════════════════════════════════════╝

SITUASI WORKFORCE SAAT INI
  Total karyawan aktif  : {total_hc:,}
  Rata-rata engagement  : {avg_engagement:.2f} / 5.0
  Sentimen review       : {avg_sentiment:+.3f} ({'positif' if avg_sentiment > 0 else 'perlu perhatian'})

FLIGHT RISK ALERT
  CRITICAL (skor >= 80%) : {critical_count} karyawan  -> intervensi segera
  HIGH (skor 60-80%)     : {high_count} karyawan  -> enhanced monitoring
  Karyawan paling berisiko: {top_risk['full_name']} ({top_risk['department']},
                            skor {top_risk['flight_risk_score']:.1%})
  Central Connector berisiko: {len(cc_at_risk)} orang -> dampak jaringan signifikan

KESEHATAN ORGANISASI
  Network density        : rendah (0.0008) -> potensi silo tinggi
  Community detection    : silo risk terdeteksi di Engineering & Sales
  Sentimen trend         : {'stabil' if avg_sentiment > -0.1 else 'memburuk - perlu investigasi'}

SKENARIO TERBURUK
  Jika {scenario_worst['scenario']} terjadi:
    -> Estimasi dampak produktivitas : {scenario_worst['est_productivity_impact_pct']:.1f}%
    -> Estimasi waktu pemulihan      : {scenario_worst['est_recovery_months']:.1f} bulan
    -> Koneksi jaringan hilang       : {scenario_worst['lost_direct_connections']}

ROI PROGRAM RETENSI
  Biaya replacement jika semua resign : Rp {replacement_cost:,.0f}
  Biaya program retensi               : Rp {retention_cost:,.0f}
  Net penghematan estimasi            : Rp {net_savings:,.0f}

AGENDA TINDAKAN (bulan ini)
  1. Retention conversation untuk {critical_count} CRITICAL cases (minggu ini)
  2. Salary review untuk karyawan compa-ratio <0.85 (2 minggu)
  3. Succession planning untuk {len(cc_at_risk)} Central Connectors berisiko (bulan ini)
  4. Skills gap: isi HIGH priority gaps per L&D report (kuartal ini)

REKRUTMEN
  Time-to-fill rata-rata : {recruitment_metrics['avg_time_to_fill_days']:.0f} hari
  Source terbaik         : {recruitment_metrics['top_source_by_quality']}

[Generated by OrgPulse People Analytics Platform | Confidential]
""".strip()

    return brief


if __name__ == "__main__":
    from src.planning.scenario_simulator import run_scenario_comparison
    from src.network.ona_builder import build_employee_graph

    print("Loading data...")
    df_emp        = pd.read_csv("data/simulated/employees.csv")
    df_risk       = pd.read_csv("data/processed/flight_risk_scores.csv")
    df_centrality = pd.read_csv("data/processed/centrality_scores.csv")
    df_sentiment  = pd.read_csv("data/processed/reviews_sentiment.csv")
    df_comm       = pd.read_csv("data/simulated/communications.csv")

    print("Building scenarios...")
    G                = build_employee_graph(df_comm, df_emp, min_interactions=3)
    scenario_results = run_scenario_comparison(G, df_emp, df_centrality, df_risk)

    print("Generating executive brief...")
    brief = generate_executive_brief(
        df_employees     = df_emp,
        df_flight_risk   = df_risk,
        df_centrality    = df_centrality,
        df_sentiment     = df_sentiment,
        scenario_results = scenario_results,
    )

    print(brief)

    with open("results/reports/executive_brief_2024.txt", "w", encoding="utf-8") as f:
        f.write(brief)
    print("\n✅ Saved: results/reports/executive_brief_2024.txt")